version: '3'

services: 
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: naughts&passwords
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: naughts&passwords
    volumes:
      - db:/var/lib/postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: naughts&passwords
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db: